### ISSUE TITLE
Non-primitive values should not be put into query parameters 

### ISSUE THREAD

**Issue by blakeli0** [googleapis/gapic-generator-java#1016]
In some cases, the generated client library would put complex object to query parameters, like [here](https://github.com/googleapis/gapic-generator-java/blob/889f316d7dfcfdaf826cb8024166cc8eabeaef0d/src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonComplianceStub.golden#L176) , the proto definition for this method is [here](https://github.com/googleapis/gapic-generator-java/blob/889f316d7dfcfdaf826cb8024166cc8eabeaef0d/src/test/proto/compliance.proto#L64). The generated client library will error out during runtime if non-primitive values are put into query parameters.

Even though a rpc method definition like this should never happen, but in case it happens, we should produce errors during generation time instead of runtime.

TODO: Create a separate issue for path parameters.

**Comment by vam-google** [comment]
Valid query params can be primitives **OR** an instance of  `Duration`, ` Timestamp` or `FieldMask` or `*Value` wrapper classes (like `Int32Value`).

This is so because protobuf-json [serializaiton spec](https://developers.google.com/protocol-buffers/docs/proto3#json) defines those three classes as serializable in a form of a string, instead of in a form of a regular object.

`talent/v4` would be a real wold example: https://github.com/googleapis/googleapis/blob/master/google/cloud/talent/v4/job_service.proto#L84

the `UpdateJob` method iteslf is a weird one, because it is a patch method with query params, but nonetheless that should be transcodded as:
`UpdateJobRequest.job` - body
`UpdateJobRequest.update_mask` - query_param

and that shoud kind of work, because `FieldMask` object is serializable to a pure string according to protobuf spec

**Comment by blakeli0** [comment]
This issue is not valid anymore. Non-primitive values are allowed in query params, see [http.proto](https://github.com/googleapis/googleapis/blob/a94d5d453a09f4bc874c07b511eac77b10ea9949/google/api/http.proto#L106) for example.
