### ISSUE TITLE
Pagination support must not be generated unless all conditions are met

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator-java#1017]
Based on the contents of https://google.aip.dev/client-libraries/4233, pagination support should only be added to a GAPIC method _iff_ the following criteria are met:

```
Pagination can be inferred for an RPC when all of the following conditions are met:

* The request message contains an int32 page_size field.
* The request message contains a string page_token field.
* The response message contains a string next_page_token field.
* The response message contains one non-primitive repeated field.
```

Based on a recent report referencing http://cl/460633538, the Java generator is attempting to generate Pagination support even when the final item on that list is **not** fulfilled `The response message contains one non-primitive repeated field`. The response message in question `FetchInventoryResponse` does not have a `repeated` field, and even though it has the other pagination support fields.

**Comment by blakeli0** [comment]
This is done on purpose due to backwards compatibility reasons, due to this sentence in https://google.aip.dev/client-libraries/4233
```
Client libraries that are implementing automatic pagination must still provide access to the individual fields on the response message, in the usual fashion.
```
Also, I don't think this is in violation of the AIP since it says "Pagination can be inferred for an RPC when all of the following conditions are met", not something like "Pagination must not be inferred for an RPC when any of the following conditions are not met".
