### ISSUE TITLE
[ggj] Replace anonymous classes with lambdas in generated code

### ISSUE THREAD

**Issue by miraleung** [googleapis/gapic-generator-java#791]

**Comment by chanseokoh** [comment]
My idea was to have a general AST transformer that is independent of other components, which traverses an input AST and transforms an `AnonymousClassExpr` AST to `LambdaExpr` when it deems possible for conversion. However, I realized this approach is infeasible for many reasons.

For example, [scoping rules are different](https://www.javacodegeeks.com/2016/06/java-8-converting-anonymous-classes-lambda-expressions.html) between the anonymous classes and lambdas, so in order to make it work this way, you need full semantics analysis.

> For example, in lambda expressions, `this` and `super` are lexically scoped, meaning they are relative to the enclosing class, but in an anonymous class, they are relative to the anonymous class itself. Similarly, local variables declared in lambda expressions will conflict with variables declared in the enclosing class, but in anonymous classes, they are allowed to shadow variables in the enclosing class.

So I think it should generate `LambdaExpr` instead of `AnonymousClassExpr` at the first place.

**Comment by miraleung** [comment]
This has since been fixed in #815, and some anonymous classes cannot be lambda-ized due to multiple nested methods. Hence `AnonymousClassExpr` is still relevant in the generated client libraries.

Closing since this is specific to #815, please feel free to open a new issue for any lambda / anonymous class issues you'd like to address.
